from __future__ import annotations

from typing import Protocol

from core.laser_models import LaserChannelInfo
from core.records import PowerSnapshot, SpectralAcquisition, SpectrometerCapabilities


class SpectrometerAdapter(Protocol):
    name: str
    serial_number: str
    max_intensity: float

    def acquire_spectrum(
        self,
        *,
        integration_ms: int,
        averages: int,
        correct_dark: bool,
        correct_nonlinearity: bool,
        averaging_mode: str = "software",
    ) -> SpectralAcquisition: ...

    def capabilities(self) -> SpectrometerCapabilities: ...
    def get_ccd_temperature_c(self) -> float: ...
    def set_tec_target_c(self, temperature_c: float) -> None: ...
    def set_tec_enabled(self, enabled: bool) -> None: ...
    def close(self) -> None: ...


class PowerMeterAdapter(Protocol):
    def identify(self) -> str: ...
    def read_all_power_with_status(self) -> PowerSnapshot: ...
    def set_wavelength_for_laser_nm(self, wavelength_nm: float) -> int: ...
    def get_wavelength_nm(self) -> int: ...
    def close(self) -> None: ...


class LaserBoxAdapter(Protocol):
    port: str
    box_id: str

    def discover_channels(self, max_channels: int = 5) -> list[LaserChannelInfo]: ...
    def read_channel_info(self, channel: int) -> LaserChannelInfo: ...
    def set_power_w(self, channel: int, power_w: float) -> None: ...
    def set_enabled(self, channel: int, enabled: bool) -> None: ...
    def get_enabled(self, channel: int): ...
    def set_cdrh_delay(self, channel: int, enabled: bool) -> str: ...
    def disable_all(self, max_channels: int = 5) -> None: ...
    def close(self) -> None: ...
